const fs = require('fs');

const url = process.env.SUPABASE_URL;
const anonKey = process.env.SUPABASE_ANON_KEY;

if (!url || !anonKey) {
  console.error('Missing SUPABASE_URL or SUPABASE_ANON_KEY environment variables');
  process.exit(1);
}

const content = `// Generated by scripts/generate-config.js
window.SUPABASE_URL = "${url}";
window.SUPABASE_ANON_KEY = "${anonKey}";
window.SUPABASE_KEY = window.SUPABASE_ANON_KEY;
`;

fs.writeFileSync('config.js', content);
console.log('config.js generated');
